server:
  port: 8081

spring:
  profiles: prod


  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop


logging:
  path: /var/logs/
  file: TacoCloud.log
  level:
    root: WARN
    org:
    springframework:
    security: DEBUG

taco:
  orders:
    pageSize: 10

